# Generated by Django 4.1.7 on 2023-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="emoji",
            field=models.IntegerField(
                choices=[(0, "😡"), (1, "😔"), (2, "😐"), (3, "🙂"), (4, "🥰"), (5, "💩")]
            ),
        ),
    ]
